tables:
- name: organizations
  count: 10
  columns:
  - name: id
    type: serial
    generator: serial
    industry: base
    is_primary: true
  - name: uuid
    type: uuid
    generator: uuid
    industry: base
    unique: true
  - name: name
    type: varchar(100)
    generator: company
    industry: base
    params:
      max_length: 100
  - name: description
    type: text
    generator: paragraph
    industry: base
  - name: founded_date
    type: date
    generator: date
    industry: base
  - name: budget
    type: money
    generator: money
    industry: base
    params:
      min: 10000.0
      max: 5000000.0
  - name: is_active
    type: boolean
    generator: boolean
    industry: base
  - name: website
    type: varchar(255)
    generator: url
    industry: base
    params:
      max_length: 255
  - name: metadata
    type: jsonb
    generator: jsonb
    industry: base
    params:
      complexity: "complex"
  - name: tags
    type: text[]
    generator: pg_array
    industry: base
    params:
      element_type: "text"
      min_size: 2
      max_size: 5
  - name: employee_count_range
    type: int4range
    generator: int4range
    industry: base
  - name: created_at
    type: timestamp
    generator: datetime
    industry: base

- name: departments
  count: 25
  columns:
  - name: id
    type: serial
    generator: serial
    industry: base
    is_primary: true
  - name: org_id
    type: integer
    generator: number
    industry: base
  - name: name
    type: varchar(50)
    generator: word
    industry: base
    params:
      max_length: 50
  - name: budget
    type: money
    generator: money
    industry: base
    params:
      min: 50000.0
      max: 1000000.0
  - name: head_count
    type: integer
    generator: number
    industry: base
    params:
      min: 5
      max: 100
  - name: location_point
    type: point
    generator: point
    industry: base
  - name: office_polygon
    type: polygon
    generator: polygon
    industry: base
  - name: created_at
    type: timestamp
    generator: datetime
    industry: base

- name: employees
  count: 100
  columns:
  - name: id
    type: bigserial
    generator: bigserial
    industry: base
    is_primary: true
  - name: dept_id
    type: integer
    generator: number
    industry: base
  - name: employee_uuid
    type: uuid
    generator: uuid
    industry: base
    unique: true
  - name: first_name
    type: varchar(50)
    generator: firstname
    industry: base
    params:
      max_length: 50
  - name: last_name
    type: varchar(50)
    generator: lastname
    industry: base
    params:
      max_length: 50
  - name: email
    type: varchar(100)
    generator: email
    industry: base
    unique: true
    params:
      max_length: 100
  - name: phone
    type: varchar(20)
    generator: phone
    industry: base
    params:
      max_length: 20
  - name: salary
    type: money
    generator: money
    industry: base
    params:
      min: 30000.0
      max: 200000.0
  - name: hire_date
    type: date
    generator: date
    industry: base
  - name: birth_date
    type: date
    generator: date
    industry: base
  - name: is_manager
    type: boolean
    generator: boolean
    industry: base
  - name: profile_data
    type: json
    generator: json
    industry: base
    params:
      complexity: "simple"
  - name: skills
    type: text[]
    generator: pg_array
    industry: base
    params:
      element_type: "text"
      min_size: 1
      max_size: 8
  - name: work_schedule
    type: interval
    generator: interval
    industry: base
    params:
      type: "hours"
  - name: blood_type
    type: varchar(3)
    generator: blood_type
    industry: health
    params:
      max_length: 3
  - name: created_at
    type: timestamp
    generator: datetime
    industry: base

- name: network_devices
  count: 50
  columns:
  - name: id
    type: serial
    generator: serial
    industry: base
    is_primary: true
  - name: device_name
    type: varchar(50)
    generator: word
    industry: base
    params:
      max_length: 50
  - name: ip_address
    type: inet
    generator: inet
    industry: base
  - name: network_cidr
    type: cidr
    generator: cidr
    industry: base
  - name: mac_address
    type: macaddr
    generator: macaddr
    industry: base
    unique: true
  - name: device_config
    type: jsonb
    generator: jsonb
    industry: base
    params:
      complexity: "simple"
  - name: firmware_data
    type: bytea
    generator: bytea
    industry: base
    params:
      size: 32
  - name: location
    type: point
    generator: point
    industry: base
  - name: coverage_area
    type: circle
    generator: circle
    industry: base
  - name: uptime_range
    type: tsrange
    generator: tsrange
    industry: base
  - name: created_at
    type: timestamp
    generator: datetime
    industry: base

- name: projects
  count: 40
  columns:
  - name: id
    type: serial
    generator: serial
    industry: base
    is_primary: true
  - name: manager_id
    type: bigint
    generator: number
    industry: base
  - name: title
    type: text
    generator: sentence
    industry: base
  - name: description
    type: text
    generator: paragraph
    industry: base
    params:
      count: 2
  - name: status
    type: varchar(20)
    generator: enum
    industry: base
    values: ["planning", "in_progress", "testing", "completed", "cancelled"]
  - name: priority
    type: varchar(10)
    generator: enum
    industry: base
    values: ["low", "medium", "high", "critical"]
  - name: start_date
    type: date
    generator: date
    industry: base
  - name: end_date
    type: date
    generator: date
    industry: base
  - name: budget
    type: money
    generator: money
    industry: base
    params:
      min: 5000.0
      max: 500000.0
  - name: timeline
    type: interval
    generator: interval
    industry: base
    params:
      type: "days"
  - name: requirements
    type: jsonb
    generator: jsonb
    industry: base
    params:
      complexity: "array"
  - name: team_members
    type: integer[]
    generator: pg_array
    industry: base
    params:
      element_type: "integer"
      min_size: 2
      max_size: 10
  - name: created_at
    type: timestamp
    generator: datetime
    industry: base

- name: documents
  count: 80
  columns:
  - name: id
    type: serial
    generator: serial
    industry: base
    is_primary: true
  - name: project_id
    type: integer
    generator: number
    industry: base
  - name: title
    type: text
    generator: sentence
    industry: base
  - name: content
    type: text
    generator: paragraph
    industry: base
    params:
      count: 5
  - name: document_type
    type: text
    generator: enum
    industry: base
    values: ["specification", "design", "test_plan", "user_manual", "report"]
  - name: xml_content
    type: xml
    generator: xml
    industry: base
  - name: search_vector
    type: tsvector
    generator: tsvector
    industry: base
  - name: search_query
    type: tsquery
    generator: tsquery
    industry: base
  - name: version
    type: numeric
    generator: float
    industry: base
    params:
      min: 1.0
      max: 10.0
      precision: 1
  - name: file_data
    type: bytea
    generator: bytea
    industry: base
    params:
      size: 64
  - name: is_published
    type: boolean
    generator: boolean
    industry: base
  - name: created_at
    type: timestamp
    generator: datetime
    industry: base

- name: healthcare_records
  count: 60
  columns:
  - name: id
    type: serial
    generator: serial
    industry: base
    is_primary: true
  - name: employee_id
    type: bigint
    generator: number
    industry: base
  - name: record_type
    type: text
    generator: enum
    industry: base
    values: ["checkup", "emergency", "prescription", "lab_result", "vaccination"]
  - name: medical_data
    type: jsonb
    generator: jsonb
    industry: base
    params:
      complexity: "complex"
  - name: diagnosis
    type: text
    generator: diagnosis
    industry: health
  - name: medications
    type: text[]
    generator: pg_array
    industry: base
    params:
      element_type: "text"
      min_size: 0
      max_size: 5
  - name: vital_signs
    type: text
    generator: vital_sign
    industry: health
  - name: allergies
    type: text
    generator: allergy
    industry: health
  - name: visit_date
    type: date
    generator: date
    industry: base
  - name: follow_up_interval
    type: interval
    generator: interval
    industry: base
    params:
      type: "months"
  - name: created_at
    type: timestamp
    generator: datetime
    industry: base

- name: flight_tracking
  count: 30
  columns:
  - name: id
    type: serial
    generator: serial
    industry: base
    is_primary: true
  - name: employee_id
    type: bigint
    generator: number
    industry: base
  - name: flight_number
    type: text
    generator: flight_number
    industry: aviation
  - name: aircraft_type
    type: text
    generator: aircraft_type
    industry: aviation
  - name: origin
    type: text
    generator: airport_code
    industry: aviation
  - name: destination
    type: text
    generator: airport_code
    industry: aviation
  - name: seat_number
    type: text
    generator: seat_number
    industry: aviation
  - name: gate
    type: text
    generator: gate_number
    industry: aviation
  - name: flight_path
    type: path
    generator: path
    industry: base
  - name: departure_time
    type: timestamp
    generator: datetime
    industry: base
  - name: arrival_time
    type: timestamp
    generator: datetime
    industry: base
  - name: flight_duration
    type: interval
    generator: interval
    industry: base
    params:
      type: "hours"
  - name: status
    type: text
    generator: flight_status
    industry: aviation
  - name: created_at
    type: timestamp
    generator: datetime
    industry: base


relations:
- type: one_to_many
  from_table: organizations
  from_column: id
  to_table: departments
  to_column: org_id

- type: one_to_many
  from_table: departments
  from_column: id
  to_table: employees
  to_column: dept_id

- type: one_to_many
  from_table: employees
  from_column: id
  to_table: projects
  to_column: manager_id

- type: one_to_many
  from_table: projects
  from_column: id
  to_table: documents
  to_column: project_id

- type: one_to_many
  from_table: employees
  from_column: id
  to_table: healthcare_records
  to_column: employee_id

- type: one_to_many
  from_table: employees
  from_column: id
  to_table: flight_tracking
  to_column: employee_id