tables:
- name: profiles
  count: 12
  columns:
  - name: _id
    type: string
    generator: uuid
    is_primary: true
    is_nullable: false
  - name: username
    type: string
    generator: word
    is_nullable: false
  - name: email
    type: string
    generator: word
    is_nullable: false
  - name: bio
    type: string
    generator: sentence
    is_nullable: false
  - name: location
    type: string
    generator: word
    is_nullable: false
  - name: created_at
    type: datetime
    generator: timestamp
    is_nullable: false
    params:
      start: "2023-01-01T00:00:00Z"
      end: "2024-01-01T00:00:00Z"

- name: posts
  count: 35
  columns:
  - name: _id
    type: string
    generator: uuid
    is_primary: true
    is_nullable: false
  - name: profile_id
    type: string
    generator: foreign
    is_nullable: false
    params:
      table: profiles
      column: _id
  - name: content
    type: string
    generator: sentence
    is_nullable: false
  - name: visibility
    type: string
    generator: word
    is_nullable: false
  - name: created_at
    type: datetime
    generator: timestamp
    is_nullable: false
    params:
      start: "2023-01-01T00:00:00Z"
      end: "2024-01-01T00:00:00Z"

- name: likes
  count: 50
  columns:
  - name: _id
    type: string
    generator: uuid
    is_primary: true
    is_nullable: false
  - name: post_id
    type: string
    generator: foreign
    is_nullable: false
    params:
      table: posts
      column: _id
  - name: profile_id
    type: string
    generator: foreign
    is_nullable: false
    params:
      table: profiles
      column: _id
  - name: reaction
    type: string
    generator: word
    is_nullable: false
  - name: created_at
    type: datetime
    generator: timestamp
    is_nullable: false
    params:
      start: "2023-01-01T00:00:00Z"
      end: "2024-01-01T00:00:00Z"

relations:
- type: one_to_many
  from_table: profiles
  from_column: _id
  to_table: posts
  to_column: profile_id

- type: one_to_many
  from_table: posts
  from_column: _id
  to_table: likes
  to_column: post_id

- type: one_to_many
  from_table: profiles
  from_column: _id
  to_table: likes
  to_column: profile_id
