server:
  port: 8080
  host: "localhost"
  rate_limit: 100
  cors_origins:
  - "http://localhost:3000"
  - "https://app.example.com"
  max_file_size: 10485760 # 10MB
  job_timeout: 3600 # 1 hour
  job_cleanup: 86400 # 24 hours

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "mockcraft"
  ssl_mode: "disable"

output:
  format: "json"
  dir: "./output"
  pretty: true
